# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.URLField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('rating', models.FloatField(default=0, editable=False)),
                ('numOfRatings', models.IntegerField(default=0, editable=False)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.URLField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('audioDownload', models.URLField()),
                ('audioPlay', models.URLField()),
                ('playCount', models.IntegerField(default=0, editable=False)),
                ('downloadsCount', models.IntegerField(default=0, editable=False)),
                ('rating', models.FloatField(default=0, editable=False)),
                ('numOfRatings', models.IntegerField(default=0, editable=False)),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('vetoed', models.BooleanField(default=False)),
                ('albums', models.ManyToManyField(related_name='audios', to='sonidosLibresApp.Album')),
                ('artists', models.ManyToManyField(related_name='audios', to='sonidosLibresApp.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('relatedCategories', models.ManyToManyField(blank=True, editable=False, related_name='_category_relatedCategories_+', to='sonidosLibresApp.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Audio')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'commentaries',
            },
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('detail', models.CharField(max_length=5000)),
                ('typeConvocation', models.CharField(choices=[('PUB', 'Convocatoria Publica'), ('PRI', 'Convocatoria Privada')], default='PUB', max_length=3)),
                ('terms', models.TextField(blank=True, null=True)),
                ('dateInit', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateEnd', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateLimit', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateResults', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('U', 'Sin Publicar'), ('P', 'Publicada'), ('V', 'En Votacion'), ('C', 'Cerrada'), ('R', 'Retirada')], default='U', max_length=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Agent')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocationAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Audio')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Convocation')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocationVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Artist')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Convocation')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amount', models.FloatField()),
                ('artistReceived', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedDonations', to='sonidosLibresApp.Artist')),
                ('donorArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donationsMade', to='sonidosLibresApp.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='categories',
            field=models.ManyToManyField(related_name='audios', to='sonidosLibresApp.Category'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='albums', to='sonidosLibresApp.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='albums', to='sonidosLibresApp.Category'),
        ),
    ]
