# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-02 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0002_auto_20161102_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocation',
            name='dateEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='dateInit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='dateLimit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='dateResults',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
