# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0003_auto_20161102_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amount', models.FloatField()),
                ('artistReceived', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedDonations', to='sonidosLibresApp.Artist')),
                ('donorArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donationsMade', to='sonidosLibresApp.Artist')),
            ],
        ),
        migrations.AlterField(
            model_name='convocation',
            name='status',
            field=models.CharField(choices=[('U', 'Sin Publicar'), ('P', 'Publicada'), ('V', 'En Votacion'), ('C', 'Cerrada'), ('R', 'Retirada')], default='U', max_length=1),
        ),
    ]
