# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-12 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonidosLibresApp', '0004_auto_20161112_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 12, 22, 16, 14, 807838, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(default='Esta es una descripcion generica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='genere',
            field=models.CharField(default='M', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='nickname',
            field=models.CharField(default='Takezo Akane', max_length=250),
            preserve_default=False,
        ),
    ]
