# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonidosLibresApp', '0005_auto_20161012_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.URLField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('detail', models.CharField(max_length=5000)),
                ('terms', models.URLField()),
                ('dateInit', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateEnd', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateLimit', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateResults', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Agent')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocationAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0, editable=False)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Audio')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Convocation')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocationVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Artist')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonidosLibresApp.Convocation')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
